### PR TITLE
Integrate and test VerifyEmailToken

### PR DESCRIPTION
**Pull request by kimlisa**
Part of Task: https://github.com/hwsc-org/hwsc-user-svc/issues/78

Fail is expected after a second run of valid VerifyEmailToken test b/c service will remove the email token from database upon success on first run.

screen shot 2019-03-06 at 4 47 56 am

### CODE REVIEW

**Comment by kimlisa** [comment]
> Fail is expected after a second run of valid VerifyEmailToken test b/c service will remove the email token from database upon success on first run.
> Is there a way around this?

No, because I don't have a service that returns the email token string. 
The only way to test a success run of valid VerifyEmailToken again is to rerun the db-local-run that reseeds the data into token table.

**Comment by faraonc** [comment]
Can we `CreateUser` before `VerifyEmailToken` ?

**Comment by kimlisa** [comment]
> Can we `CreateUser` before `VerifyEmailToken` ?

CreateUser will not return a email token. None of `user-svc` services return the email token information as a response object.

**Comment by kimlisa** [comment]
Test case 17 repeatable result:

screen shot 2019-03-06 at 11 23 48 am

**Pull request merged**
